name: .NET MAUI Build and Test

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 7.0.401  # La versión puede variar, verifica la última establecida

    - name: Restore Android workloads
      run: dotnet workload restore --project FerMovilix/FerMovilix/FerMovilix.csproj::TargetFramework=net7.0-android

    - name: Restore Tizen workloads
      run: dotnet workload restore --project FerMovilix/FerMovilix.Core/FerMovilix.Core.csproj::TargetFramework=net7.0

    - name: Restore dependencies
      run: dotnet restore

    - name: Build for Android
      run: dotnet build -t:Run -f net7.0-android

    - name: Build
      run: dotnet build --configuration Release

    - name: Test
      run: dotnet test --no-build --verbosity normal

